fastify/fastify-secure-session

README.md
index.js
package.json
test/path.js

Check if path is added correctly.

---

index.js
package.json

Join the `onRequest` hook party! 🎉

Use onRequest hook instead of preHandler

---

README.md
index.js
test/secret.js

I committed by --no-verify flag. When pre-commit hook  tried to run npm test there was errors.
But when I run it by myself all of test passes.

bug in checking salt length is fixed

---

README.md
index.js
test/key-rotation.js

Attempted implementation to support key rotation.
Todo (if this is acceptable as a feature):

support and tests for key rotation via key as an array

---

index.d.ts
package.json
test-d/index.test-d.ts

- adds `index.d.ts`
- adds a simple regression test using `tsd`
- bumps the dependency on `fastify-cookie` to a version who's types play nice with Fastify 3
Tested locally in my project and works good for me!

Add TypeScript types

---

README.md
index.js
test/nonce-bad-length.test.js

As titled :)
I've also added `debug` logs to improve the debugging experience.

Added check for nonce length

---

README.md

Adding neccessary path key to cookie config in examples.

---

README.md

Added info in README about using keys as hex strings

---

README.md

chore: update docs about security

---

README.md

remove superfluous curly brace in code example

---

README.md
index.d.ts
test-d/index.test-d.ts

feat: add typed session data support (#115)

---

README.md
index.d.ts
index.js
test-d/index.test-d.ts
test/access.js

Related to https://github.com/fastify/fastify-secure-session/issues/118
If you have any ideas on how to display this one in documentation (I couldn't figure out where to place it..)

feat: add get all data

---

package.json

Fixes command when running with `npx "@fastify/secure-session"`

fix: command

---

.github/workflows/ci.yml
index.js
package.json

bumped Fastify v4

---

test/secret.js

This PR improves test coverage.
before:
```
$ npm test
> @fastify/secure-session@5.1.0 test
> standard && tap test/*.js && tsd
PASS  test/decorators.js 9 OK 66.974ms
PASS  test/delete.js 14 OK 201.459ms
PASS  test/cookie-name.js 6 OK 202.445ms
PASS  test/dynamic-cookie-options.js 13 OK 225.886ms
PASS  test/access.js 20 OK 240.085ms
PASS  test/key.js 8 OK 230.739ms
PASS  test/key-rotation.js 11 OK 250.853ms
PASS  test/key-base64.js 5 OK 199.263ms
PASS  test/malformed-cookie.js 5 OK 177.691ms
PASS  test/nonce-bad-length.test.js 5 OK 141.767ms
PASS  test/path.js 4 OK 151.018ms
PASS  test/salt.js 5 OK 146.278ms
PASS  test/schema.js 6 OK 171.06ms
PASS  test/secret.js 15 OK 2s
🌈 SUMMARY RESULTS 🌈 …
```

chore: improve coverage for secret option

---

test/secret.js

This PR improves test coverage.

chore: improve coverage for options.salt

---

test/key.js

This PR improves test coverage.
before:
```
$ npm test
> @fastify/secure-session@5.1.0 test
> standard && tap test/*.js && tsd
PASS  test/decorators.js 9 OK 55.92ms
PASS  test/cookie-name.js 6 OK 172.394ms
PASS  test/key-base64.js 5 OK 175.017ms
PASS  test/key-rotation.js 11 OK 185.281ms
PASS  test/key.js 8 OK 197.355ms
PASS  test/dynamic-cookie-options.js 13 OK 201.475ms
PASS  test/delete.js 14 OK 183.093ms
PASS  test/access.js 20 OK 211.846ms
PASS  test/malformed-cookie.js 5 OK 151.069ms
PASS  test/nonce-bad-length.test.js 5 OK 108.988ms
PASS  test/path.js 4 OK 108.931ms
PASS  test/schema.js 6 OK 126.143ms
PASS  test/salt.js 5 OK 111.035ms
PASS  test/secret.js 21 OK 2s
🌈 SUMMARY RESULTS 🌈 …
```

chore: improve coverage for options.key type

---

test/key.js

before:
```
$ npm test
> @fastify/secure-session@5.1.0 test
> standard && tap test/*.js && tsd
PASS  test/decorators.js 9 OK 53.313ms
PASS  test/key-base64.js 5 OK 220.349ms
PASS  test/cookie-name.js 6 OK 205.014ms
PASS  test/key-rotation.js 11 OK 270.789ms
PASS  test/key.js 10 OK 230.276ms
PASS  test/access.js 20 OK 265.417ms
PASS  test/delete.js 14 OK 198.307ms
PASS  test/dynamic-cookie-options.js 13 OK 258.888ms
PASS  test/malformed-cookie.js 5 OK 193.168ms
PASS  test/nonce-bad-length.test.js 5 OK 137.843ms
PASS  test/salt.js 5 OK 147.088ms
PASS  test/path.js 4 OK 140.554ms
PASS  test/schema.js 6 OK 166.027ms
PASS  test/secret.js 21 OK 3s
🌈 SUMMARY RESULTS 🌈
Suites:   14 passed, 14 of 14 …
```

improve coverage for options.key existence

---

test/decorators.js

before:
```
$ npm test
> @fastify/secure-session@5.1.0 test
> standard && tap test/*.js && tsd
PASS  test/decorators.js 9 OK 41.229ms
PASS  test/cookie-name.js 6 OK 168.487ms
PASS  test/key-base64.js 5 OK 168.367ms
PASS  test/delete.js 14 OK 166.961ms
PASS  test/access.js 20 OK 205.971ms
PASS  test/key-rotation.js 11 OK 183.691ms
PASS  test/dynamic-cookie-options.js 13 OK 174.026ms
PASS  test/key.js 12 OK 198.419ms
PASS  test/malformed-cookie.js 5 OK 141.524ms
PASS  test/nonce-bad-length.test.js 5 OK 112.986ms
PASS  test/salt.js 5 OK 116.898ms
PASS  test/path.js 4 OK 117.56ms
PASS  test/schema.js 6 OK 143.425ms
PASS  test/secret.js 21 OK 2s
🌈 SUMMARY RESULTS 🌈
Suites:   14 passed, 14 of 14 …
```

chore: improve coverage for the case that the cipher that is not long enough

---

index.js
package.json
test/fastify-cookie.js

chore: check if fastify/@cookie is already registered

---

.npmrc

disable package-lock-generation

---

package.json
types/index.d.ts
types/index.test-d.ts

move types into types folder, replace use of FastifyPlugin with FastifyPluginCallback

---

.github/workflows/ci.yml
package.json

create npm script for lint and activate lint and license-check in ci.yml

---

index.js
test/decorators.js

update logging messages to current package name
